/* Generated By:JavaCC: Do not edit this line. ValidationDSLConstants.java */
package dsl.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ValidationDSLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CEP = 1;
  /** RegularExpression Id. */
  int CPF = 2;
  /** RegularExpression Id. */
  int CNPJ = 3;
  /** RegularExpression Id. */
  int NAME = 4;
  /** RegularExpression Id. */
  int EMAIL = 5;
  /** RegularExpression Id. */
  int STRING_LITERAL = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<CEP>",
    "<CPF>",
    "<CNPJ>",
    "<NAME>",
    "<EMAIL>",
    "<STRING_LITERAL>",
  };

}
