/* Generated By:JavaCC: Do not edit this line. ValidationDSLConstants.java */
package com.plp.attributevalidatorapi.dsl.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ValidationDSLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CEP = 6;
  /** RegularExpression Id. */
  int CPF = 7;
  /** RegularExpression Id. */
  int CNPJ = 8;
  /** RegularExpression Id. */
  int NAME = 9;
  /** RegularExpression Id. */
  int EMAIL = 10;
  /** RegularExpression Id. */
  int STRING_LITERAL = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"cep\"",
    "\"cpf\"",
    "\"cnpj\"",
    "\"name\"",
    "\"email\"",
    "<STRING_LITERAL>",
  };

}
